name: CI/CD

on:
  push:
    paths:
      - 'site/index.html'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: devops-challenge-20240202

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy index.html to EC2 via SCP
      run: |
        scp -o StrictHostKeyChecking=no site/index.html ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/tmp/index.html

    - name: Move index.html to nginx folder and restart nginx
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          sudo mv /tmp/index.html /var/www/html/index.html
          sudo systemctl restart nginx
        EOF
